src/CplexSolverInterface.jl
Need to set `has_int` and `has_qc` when appropriate.
Somewhat related: not sure if `has_qc` should be true if only the objective is quadratic (QP, MIQP).
Both `CPXlpopt()` and `CPXqpopt()` accept the model, but I haven't checked if they actually do the same thing or maybe use a different method (possibly different defaults).
=> Check problem type after reading from file

src/CplexSolverInterface.jl, src/cpx_solve.jl
Implements `MathProgBase.getnodecount` and deletes duplicate function `getnodecnt`.
Also, `get_node_count` shouldn't throw an error if node count is 0.
See JuliaOpt/JuMP.jl#442
=> implement getnodecount, don't throw error for 0 nodes

src/cpx_model.jl, src/cpx_solve.jl
these lines generate deprecated warnings with julia 0.4
=> int(x) warnings suppressed

src/cpx_vars.jl
Mixed-integer conic problems were broken through cplex because the conic to quadratic wrapper introduces extra variables but doesn't intercept ``setvartype!``.
CC @emreyamangil
=> allow length(vtype) < nvars

src/CplexSolverInterface.jl, src/cpx_callbacks.jl
First, thanks a lot for all these wonderful and truely useful tools!
Having re-coded some algorithm using _local_ lazy constraints* with Julia/JuMP, here is a suggestion of very small additions handling them in JuMP/MathProgBase/CPLEX (joint additions, cf the forks at https://github.com/madanim). As far as I know, this feature is only avalaible in CPLEX and XPress MP.
It simply consists in duplicating the current mechanics for lazy constraints and user cuts, and using the CPLEX naming convention, appending 'local' or 'Local' where applicable: e.g. '@addLazyConstraintLocal' instead of '@addLazyConstraint', etc (in the CPLEX C Api the variant is 'cutcallbackaddlocal' instead of 'cutcallbackadd').
Do you think this way of proceeding is consistent with the packages design, or would it be …
=> support for _local_ lazy constraints and user cuts (cplex)

src/CplexSolverInterface.jl
Since ABORT is only in 
`:CPX_STAT_ABORT_TIME_LIM`
but TIME_LIM is in all those
```
:CPX_STAT_ABORT_TIME_LIM
:CPXMIP_TIME_LIM_FEAS,
:CPXMIP_TIME_LIM_INFEAS,
```
This should fix the issue mentioned by @mlubin in #77
=> :UserLimit is now returned when cplex status contains TIME_LIM and not ABORT

deps/build.jl, src/CPLEX.jl, src/CplexSolverInterface.jl, src/cpx_env.jl, src/cpx_highlevel.jl, src/cpx_model.jl, src/cpx_params.jl, src/cpx_vars.jl
This pull request improves the deprecation of ASCIIString introduced in https://github.com/JuliaOpt/CPLEX.jl/pull/82 addressses and closes https://github.com/JuliaOpt/CPLEX.jl/issues/86.
Compat.ASCIIString is an alias for `ASCIIString` on Julia 0.4 and `String` on Julia 0.5.
CPLEX seems to handle non-ascii strings pretty well. The param getters and setters fail with key not found due to the `paramName2Index` dictionary lookup. Setting the model and variable name with non-ascii strings and writing them to a non-ascii filename all seems to work.
The only issues I ran into were not ASCIIString related
- `set_logfile` gives a `no method matching unsafe_convert(::Ptr{Void}, ::CPLEX.Env)`
and
- `read_model(m::Model, filename::String)` gives `CPLEX Error 1434` which is a [bad …
=> Change to Compat.ASCIIString

src/CplexSolverInterface.jl
This was causing CPLEX to fail here: https://github.com/JuliaOpt/JuMP.jl/blob/58dc38dae598652d1fee460666f31f0e5c962e05/test/callback.jl#L304
=> fix return status when exiting from callbacks

src/CplexSolverInterface.jl, src/cpx_env.jl, src/cpx_model.jl, test/env.jl, test/runtests.jl
I first tried the `finalize_env` mechanism used in Gurobi.jl but it gave me segfault because it happened that the model that is thrown away gets gc'd second which cause it to be freed after the environment has already been freed by the new model that was gc'd first.
=> fix multiple loadproblem! calls

src/CplexSolverInterface.jl, src/cpx_model.jl, test/problemtype.jl, test/runtests.jl
Changing the variable type doesn't automatically change the problem type. There needs to be an explicit call to `chgprobtype`.
Closes https://github.com/JuliaOpt/CPLEX.jl/issues/110
Passes all tests locally.
=> Fix bug that occurs when switching between integer and non-integer models

src/CplexSolverInterface.jl
This is a quick fix so that I can go ahead with releasing JuMP. JuMP calls ``setvartype!`` before ``setwarmstart!`` so it won't change behavior for JuMP users.
Closes #113
=> don't set warmstart if we don't know problem is MIP (#113)

src/CplexSolverInterface.jl, src/cpx_constrs.jl, src/cpx_model.jl, test/runtests.jl, test/sos.jl
In a model with SOS constraints but no explicit binary or integer variables, changing the problem type to `:LP` discarded the SOS constraints.
=> Fix handling of SOS and problem type. Fixes #116

src/cpx_model.jl, test/miqcp.jl, test/runtests.jl
Because the `rev_type_map` dict had two entries for `:MIQP` it was actually trying to set it as a fixed MIQP.
=> Fix handling of MIQP problem type. Fixes #115

src/CPLEX.jl, src/CplexSolverInterface.jl, src/cpx_solve.jl
We are implementing a new package BlockJuMP to define block decompositions for MIPs. It will also  define oracles to the solve the subproblems and other useful directives. See an example here: https://realopt.github.io/BlockJuMP.jl/latest/basic.html.
Cplex is one of the solvers that is already supporting benders decomposition and we would like to use it with BlockJuMP. What do you think about it ?
=> WIP: adding cplex annotations to be used for bender decomposition

README.md, deps/build.jl
Fix #128 by using the `CPLEX_STUDIO_BINARIES` environment variable on Unix so that it is possible to do:
```
$ CPLEX_STUDIO_BINARIES=/path/to/cplex/bin/x86-64_linux julia -e 'Pkg.build("CPLEX")'
```
=> Add CPLEX_STUDIO_BINARIES ENV on unix #128

src/cpx_common.jl
Passes tests on Windows Julia-0.5 and Julia-0.6
=> Fix for windows and v0.6

src/CPLEX.jl
@chriscoey has been experiencing some world age issues involving CPLEX from Pajarito.
I don't believe something like ``eval(current_module(), Expr(:import,:JuMP))`` is allowed anymore, for the same reason that we got rid of default solvers. I'd propose to disable the undocumented "JuMPfunctions" on Julia 0.6, and if they're needed they can be moved into a separate package.
@joehuchette
=> disable JuMPfunctions on Julia 0.6

src/cpx_common.jl
this is a bit of a guess, it may have been 18754, but this cutoff is closer to right
than the first commit after 0.5 branched
=> specific version cutoff for escaping stdcall

REQUIRE
We can't tag a new release supporting 0.5.
=> Drop Julia 0.5

deps/build.jl, src/CPLEX.jl
=> Fix Libdl moved to stdlib on v0.7

deps/build.jl
The most recent download of Cplex in linux (ubuntu) has the .so file with version number "1280".
=> Update build.jl to enable Cplex 12.8 support in linux

README.md
- Fixed the name of the IBM product that contains the CPLEX solver.
- Updated the URLs to the product page and where to find the trial and Academic Initiative versions.
=> Update naming and URLs for CPLEX

REQUIRE, src/MOIWrapper.jl, test/MOIWrapper.jl
Tests are passing with LQOI master. As JuliaOpt/GLPK.jl#74, it can be merged once LQOI is tagged.
Next step will be to update to julia 1.0
=> Minor updates for moi06

src/CplexSolverInterface.jl
Two more instances of a missing prefix. I scanned the rest of the file so I think we have them all.
But, I don't have a local CPLEX installation so haven't tested.
Closes https://github.com/JuliaOpt/MathProgBase.jl/issues/228
=> Add MathProgBase prefix

src/CplexSolverInterface.jl, src/cpx_model.jl
Using read_model and optimize! on MILP get ERROR: CPLEX.CplexError(1017, "CPLEX Error  1017: Not available for mixed-integer problems.\n")
Corrections on MathProgBase.loadproblem! shouldn't be directly on read_model?
=> read_model - has_int and has_qc

src/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
Turns out that the `MOIT.lintest` wasn't included. That would have caught the typo.
=> Fix bug in sense of vector sets

src/MOI_wrapper.jl, src/cpx_quad.jl, src/cpx_solve.jl, test/MathOptInterface/MOI_wrapper.jl
This PR addresses the issue #217, that is, add quadratic support in MOI_wrapper using LinQuadOptInterface.
It follows the recommendations of @odow see [discourse discussion about the subject](https://discourse.julialang.org/t/quadratic-programming-problem-cpl/21068).
I added two c_api functions to access primal and dual quadratic constraints values.
I added a get_qconstr function to get quadratic constraints through C api as well.
It adds the MOI contquadratic tests in the tests folder.
1 test fails in linear10. I do not think my changes are responsible.
4 tests fail in qcp1. I do not understand why yet as the following example does not reproduce the failures.
```julia
using JuMP, CPLEX
m = Model(with_optimizer(CPLEX.Optimizer))
@variable(m, x)
@variable(m, y)
A = [-1 1; 1 1]
c1 = …
```
=> Quadratic support in MOI

src/MOI_wrapper.jl, src/cpx_model.jl, test/C_API/iis.jl, test/MathOptInterface/MOI_wrapper.jl
First step for https://github.com/JuliaOpt/JuMP.jl/issues/1035: implement the IIS/conflict within the CPLEX package. 
For now, quite basic: call the conflict refiner, store the information it returns in a structure (allocated only when needed, so that the overhead for people not using it is just one pointer per model).
Next, I will implement MOI attributes that call these functions (if the `conflict` member of `Model` is `nothing`, call the conflict refiner and retrieve its result; if the member is already available, just return the data from it). One question I have for now: I guess the model object may be reused; what happens when it is updated (for instance, the first model is infeasible; the user removes the culprit constraint, then resolves; say they call the conflict refiner again, …
=> Compute conflict/IIS

README.md
As of CPLEX version 12.9 the use of the CPLEX shared libraries is
explicitly supported on all platforms. See the release note at
https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.studio.help/CPLEX/ReleaseNotes/topics/releasenotes1290/newLinkingNonWindows.html
and the instructions at
https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.studio.help/CPLEX/ReleaseNotes/topics/releasenotes1290/PLUGINS_ROOT/ilog.odms.cplex.help/CPLEX/UsrMan/topics/APIs/C/link_non_win_intro.html
=> Remove note about use of CPLEX shared libraries not being supported.

.travis.yml, Project.toml, deps/build.jl
I'm embarking on a CPLEX.jl re-write.
Step 1: get CPLEX running on Travis
Step 2: write the MOI wrapper
Step 3: replace the existing C wrapper with one generated by Clang.jl
Step 4: change MOI wrapper as needed to account for the Clang wrapper.
The `libcplex.so` is currently stored in a public storage provider accessible with the correct URL, which is stored in a secured environment variable:
https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings
By default, Pull Requests that come from a fork of this repo can't access the `SECRET_URL_KEY` so they will fail: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
Thus, only JuliaOpt members with commit access can trigger builds using the CPLEX binary. This isn't a good …
=> Test CPLEX on travis

README.md, deps/build.jl
Closes #97. I don't know why we enforced the path to contain `cplex`.
Closes #259. This appears to be a hold out from an early version of the install script https://github.com/JuliaOpt/CPLEX.jl/commit/83628ed5aa7584feeb3ebc4140b87be17ca264c8.
I tested on OSX, and we don't need this.
=> Fix install and README

Project.toml, deps/build.jl, test/runtests.jl
CPLEX's binary dependency is preventing us from meeting the auto-merge standards. This could be resolved by distributing the community edition.
However, in the meantime, [@fredrikekre suggested](https://github.com/JuliaRegistries/General/pull/5236#issuecomment-552646659) that we just skip the tests if we detect we're being called from GitHub Actions.
=> Skip install/test for GitHub Actions

deps/build.jl, test/runtests.jl
The issue is that it isn't sufficient to skip the build and test phases.
It is also necessary to skip the `import CPLEX` line, which I don't
know how to do without some ugly hacks. Therefore, just delete the
registry detection code. This will necessitate manual merges on the Julia
registry; oh well.
This will be fixed when we distribute the community edition.
=> Remove General Registry checks.

src/MOI/MOI_wrapper.jl
Arised from a discussion with @odow and @mlubin.
MOI.delete already has a fallback method for a vector of variable parameters (which just calls the single variable delete over each variable of the vector). In Gurobi, the problem is that this fallback has O(n^2) performance the way the things are now; in CPLEX the problem is smaller but, if an user tries to delete one or more intervals of a large number of contiguously indexed variables, then the current code does not take advantage of the fact CPLEX is optimized to do this natively. The proposed change creates the smallest list of intervals and then call delete on them in reverse order (just to minimize the variable block shifts inside CPLEX, if they are done, but also because this simplifies the code that compute the correspondence …
=> Specialization of MOI.delete for vector of variables

Project.toml, src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
https://github.com/JuliaOpt/MathOptInterface.jl/pull/1056 is merged and will be included in the next MOI release.  
Several return codes are not yet in MOI, though. Should they be included in MOI?
=> Update IIS support to MOI 0.9.14.

src/MOI/MOI_callbacks.jl, src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_callbacks.jl
Attempting to match https://github.com/jump-dev/Gurobi.jl/pull/349
I couldn't get [CTRL+C] to work for models without a callback, or from the command line. The previous intercept code had been disabled for Julia 0.7, https://github.com/jump-dev/CPLEX.jl/pull/184#discussion_r223343622,  https://github.com/jump-dev/CPLEX.jl/commit/22727b7d4a0cff7c6558f69e9b2550ee6625b456. So this is a strict improvement.
=> Refactor callback aborts

src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
=> Implement QCQP duals

src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
=> Round bounds for ZeroOne variables to avoid CPLEX warning

src/MOI/MOI_callbacks.jl, test/MathOptInterface/MOI_callbacks.jl
Raised on Discourse: https://discourse.julialang.org/t/jump-cplex-retrieve-value-of-array-variables-in-callback/54933/3
=> Allow broadcasting in callbacks

deps/build.jl
New version of #358, normally CI should work here.
=> Provide a more useful error message to user if no CPLEX binary is found. 

deps/build.jl
By mistake, I downloaded a version of CPLEX Enterprise Server. The difference is that CPLEX Enterprise Server comes with a software server to run CPLEX, but it bundles a complete copy of CPLEX Studio (in a different folder). This PR also looks for the standard Enterprise Server location.
=> Support both CPLX Studio and Enterprise Server

src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
PR spawned from issue #361. It is basically the same that was done for Gurobi.jl issue [397](https://github.com/jump-dev/Gurobi.jl/issues/397) and PR [398](https://github.com/jump-dev/Gurobi.jl/pull/398). The tests pass:
[![2021-03-10-12-03-29-1920x1080.png](https://i.postimg.cc/1z5jF22q/2021-03-10-12-03-29-1920x1080.png)](https://postimg.cc/cv2hy9sx)
=> Out-of-memory error now is a termination status.

deps/build.jl
@odow What do you think of this refactor? As discussed in https://github.com/jump-dev/CPLEX.jl/issues/368#issuecomment-836072629, it favours the CPLEX environment variables. Mostly, it really separates the different sources for the CPLEX lib. 
@ArmandoGuarnaschelli Can you make this PR work better than the current 0.7.7?
=> Refactor the build script to give priority to CPLEX environment variables

Project.toml, src/MOI/MOI_callbacks.jl
Backporting #376 so that it can be released as 0.7.8 for use with JuMP 0.21.
=> Backport bugfix in CPXcallbackpostheursoln

src/MOI/MOI_wrapper.jl
Caching CPLEX primal solution to avoid repeated calls to CPXgetx
(largely inspired from what was done on Cbc)
Should fix https://github.com/jump-dev/CPLEX.jl/issues/371
**Before**
```
julia> optimize(Model(CPLEX.Optimizer))
11.440209 seconds (1.20 M allocations: 22.125 MiB)
2-dimensional DenseAxisArray{Float64,2,...} with index sets:
Dimension 1, ["a", "b", "c", "d", "e"]
Dimension 2, Base.OneTo(20000)
```
**After**
```
julia> optimize(Model(CPLEX.Optimizer))
0.155641 seconds (1.20 M allocations: 22.888 MiB)
2-dimensional DenseAxisArray{Float64,2,...} with index sets:
Dimension 1, ["a", "b", "c", "d", "e"]
Dimension 2, Base.OneTo(20000)
```
**Script**
```
using Distributed
using JuMP
using CPLEX
using Profile
function optimize(model)
NV = 20000
set = ["a", "b", "c", "d", "e"] …
```
=> performance issues

src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
Found by https://discourse.julialang.org/t/jump-cplex-attribute-error-for-getting-cpx-param-intsollim/77595
=> Fix typo in get for RawOptimizerAttribute

Project.toml, src/MOI/MOI_wrapper.jl
Closes https://github.com/jump-dev/CPLEX.jl/issues/392
=> [Performance] don't pass names by default

src/MOI/MOI_wrapper.jl, test/MathOptInterface/MOI_wrapper.jl
x-ref: https://github.com/jump-dev/CPLEX.jl/pull/393#discussion_r841092275
cc @blegat @joaquimg
=> Convert pass_names to AbstractOptimizerAttribute

README.md
Closes #408 
My guess is that our friend `Clong` is `Int64` on nix and `Int32` on Windows. CPLEX really wants `Clonglong` here, which is the `CPXLONG` constant.
=> [README] update annotations with correct types

Project.toml, src/CPLEX.jl
I don't have 22.1.1 installed so I didn't test, but the changelog is very sparse: https://www.ibm.com/docs/en/icos/22.1.1?topic=2211-release-notes-cplex, so I assume that this will work.
Closes #415
=> Add support for v22.1.1

src/MOI/MOI_wrapper.jl
=> Fix bug in which old mipstarts are not deleted

Project.toml
I don't foresee any breaking changes and Gurobi.jl is also v1.0 now: https://github.com/jump-dev/Gurobi.jl/pull/505. So let's hit the button.
=> Prep for v1.0.0

src/MOI/indicator_constraint.jl
Found by https://github.com/jump-dev/MathOptInterface.jl/pull/2328
=> Fix get ConstraintFunction for Indicator constraints
