jump-dev/CPLEX.jl

examples/branch_jump.jl
src/CplexSolverInterface.jl

I tried the branch callback to quickly implement a branching rule I had in mind, fixed a couple of obvious bugs (also in the example, that was not updated). Not sure everything's ok (and I doubt I'll test/use this feature further), but the example should work now, at least.

Branch callback

---

src/CplexSolverInterface.jl
test/solvetime_01.jl

added getsolvetime

---

src/cpx_constrs.jl

needed an extra boolean argument that was missing for complement indicator constraints

added complement to indicator constraint

---

examples/tsp.jl

There have been some updates in JuMP. Make the examples/tsp.jl run, again...

Fix TSP example

---

src/cpx_vars.jl

wrapper for chgcolname

---

REQUIRE
deps/build.jl
src/CPLEX.jl

I finally ran into the issue at #71, so time to dump BinDeps.
@joehuchette, I don't have a mac at the moment, could you help test this?
Still need to test on windows.
Closes #71 #15
CC @tkelman @schalil

manual script instead of bindeps

---

src/CplexSolverInterface.jl

ref: https://github.com/JuliaOpt/JuMP.jl/pull/814

Fire info callbacks in all states and maintain state information

---

src/CPLEX.jl
src/cpx_constrs.jl
src/cpx_env.jl
src/cpx_highlevel.jl
src/cpx_model.jl
src/cpx_params.jl
src/cpx_quad.jl

This passes tests locally. 
Side note for interest. These deprecations caused a 2500% slow down in my algorithm run time because we are solving thousands of tiny LPs pertubing the RHS coefficients...

Deprecation updates for Julia 0.5

---

src/CplexSolverInterface.jl
test/mathprog.jl

@mlubin Copied from https://github.com/JuliaOpt/Gurobi.jl/pull/65

Implement solver independent parameters

---

src/cpx_quad.jl

JuliaOpt/JuMP.jl#877
CC @rb004f

shouldn't ignore empty quadratic constraints if there's a linear part

---

src/cpx_quad.jl

Debugging from solving https://github.com/JuliaOpt/JuMP.jl/issues/890

don't ignore empty quadratic objectives

---

src/cpx_common.jl
src/cpx_constrs.jl
src/cpx_quad.jl
src/cpx_solve.jl
src/cpx_vars.jl

This gets CPLEX passing its own tests on 0.5 and 0.6. It also passes all of JuMP's tests except for a nice segfault at the end...

Fix on 0.6

---

src/cpx_params.jl

cc @mlubin does this seem right?

Fix passing of string parameters

---

README.md
src/CplexSolverInterface.jl
src/cpx_model.jl

Useful for Pajarito.
CC @chriscoey

expose the effortlevel parameter through CplexSolver()

---

src/CplexSolverInterface.jl

Removes some unnecessary O(n) passes in the callback. Also looks like the implementation of ``cbgetlpsolution`` was incorrect; it should be returning the vector given to the callback instead of calling ``CPXgetcallbacknodex``.
@chriscoey

efficiency improvements in heuristic callback

---

src/cpx_callbacks.jl

Left out of 5dfd745c2c167bdcceac9f23e8234428ea442397
@chriscoey, see if this fixes the issue

fix for 0.6

---

examples/tsp.jl

@addlazyconstraint  --> @lazyconstraint

syntax correction on lazyconstraint

---

deps/build.jl

Closes https://github.com/JuliaOpt/CPLEX.jl/issues/190

contains -> occursin

---

src/cpx_env.jl

Fix error handling

---

README.md

Highlight unofficial nature of wrapper in readme

---

src/CplexSolverInterface.jl
src/cpx_callbacks.jl

I found some lines that returned errors in Julia 1.1.0, and fixed them to make compatible with Julia 1.1.0 and backward too.

compatibility issues

---

README.md

Clarify installation of Windows

---

src/MOI_wrapper.jl
test/MathOptInterface/MOI_wrapper.jl

[MOI] Fix handling of parameters

---

src/cpx_vars.jl
test/C_API/mip_01.jl

Resolves the problem identified in https://github.com/JuliaOpt/CPLEX.jl/pull/207#discussion_r247956932

Fix handling of model.has_int

---

REQUIRE
deps/build.jl
src/CPLEX.jl
src/CplexSolverInterface.jl
src/cpx_common.jl
src/cpx_env.jl
src/cpx_model.jl
test/runtests.jl

fix Base warning

---

src/cpx_model.jl

fix free_problem

---

.gitignore
Project.toml
REQUIRE

This patch adds `Project.toml` generated by Pkg.jl's `gen_project.jl` script
and removes `REQUIRE` file.

Add Project.toml

---

deps/build.jl
src/CPLEX.jl
src/cpx_common.jl
src/cpx_env.jl

This should ease installation in some cases.

Check for CPLEX in the PATH environment variable

---

Project.toml

In anticipation of a package release.

Add bounds in Project.toml

---

Project.toml
deps/build.jl
test/runtests.jl

Add another work-around for General registry

---

Project.toml
src/MOI/MOI_callbacks.jl
test/MathOptInterface/MOI_callbacks.jl

x-ref https://github.com/JuliaOpt/Gurobi.jl/pull/283

Add missing supports for Callbacks

---

Project.toml

The tests are currently using Random, which is not added to the project.

add Random to test

---

src/MOI/MOI_wrapper.jl
test/MathOptInterface/MOI_wrapper.jl

Fix handling of discrete->continuous models

---

src/MOI/MOI_wrapper.jl

Not sure if the title mention notifies, so... @blegat

Added comment asked by @blegat.

---

src/MOI/MOI_wrapper.jl

Replace assert error with MOI.UNKNOWN_RESULT_STATUS in get(DualStatus)

---

src/MOI/MOI_callbacks.jl

Add error for callbacks on Win32

---

src/MOI/MOI_wrapper.jl
test/MathOptInterface/MOI_wrapper.jl

Add support for ConstraintBasisStatus

---

test/MathOptInterface/MOI_wrapper.jl

Add test for CPXPARAM_OptimalityTarget

---

Project.toml
README.md
deps/build.jl

Clarify that the minimum supported version is 12.10

---

Project.toml
deps/build.jl
src/CPLEX.jl

Based on a suggested work-around by maintainers:
https://github.com/JuliaRegistries/RegistryCI.jl/issues/283#issuecomment-715362834

Add checks for RegistryCI AutoMerge

---

src/deprecated_functions.jl

Like https://github.com/jump-dev/Gurobi.jl/pull/368. Not sure why this wasn't included automatically.

Deprecate CplexSolver

---

Project.toml
src/MOI/MOI_callbacks.jl
test/MathOptInterface/MOI_callbacks.jl

Support MOI.CallbackNodeStatus

---

deps/build.jl

Fix default discovery of v20.1

---

src/MOI/MOI_callbacks.jl

Fix bug in CPXcallbackpostheursoln

---

src/MOI/MOI_wrapper.jl

Fix return type of solution attributes

---

.github/workflows/ci.yml
test/MathOptInterface/MOI_wrapper.jl

I think this will probably fail, but I don't have CPLEX installed locally.

Update CI to new LTS

---

LICENSE
deps/build.jl
scripts/clang.jl
src/CPLEX.jl
src/MOI/MOI_callbacks.jl
src/MOI/MOI_wrapper.jl
src/MOI/conflicts.jl
src/MOI/indicator_constraint.jl
src/gen1210/libcpx_api.jl
src/gen1210/libcpx_common.jl
src/gen2010/libcpx_api.jl
src/gen2010/libcpx_common.jl
test/MathOptInterface/MOI_callbacks.jl
test/MathOptInterface/MOI_wrapper.jl
test/runtests.jl

The need for this came up in some work that will soon be publicly released. I think we should do it in all the JuMP-dev repos.
cc @lschork2
cc @joehuchette

Add license headers

---

src/MOI/MOI_callbacks.jl

This would simplify https://discourse.julialang.org/t/error-using-cpxcallbackgetrelaxationpoint-at-cplex-jl-solver-specifc-callback/86230

Call load_callback_variable_primal in BRANCHING callback

---

Project.toml
src/MOI/MOI_wrapper.jl

As far as I can tell, this needs MOI v1.7

Add support for Absolute and Relative gap tolerances

---

src/MOI/MOI_wrapper.jl
test/MathOptInterface/MOI_wrapper.jl

Fix infeasibility certificate tests

---

src/MOI/MOI_wrapper.jl
test/MathOptInterface/MOI_wrapper.jl

Fix get RelativeGap when problem is not a mixed-integer problem

---

deps/build.jl

x-ref https://github.com/jump-dev/SolverTests/pull/24

Tweak ENV checks in build.jl

---

README.md

Clarify how to set options in README

---

Project.toml

x-ref https://github.com/jump-dev/ECOS.jl/pull/146

Support CEnum@0.5

---

README.md

x-ref https://github.com/jump-dev/JuMP.jl/issues/3701

Add indicator constraint to README

---

README.md

Suggested by @dourouc05 and an interaction he had with a user.

Add Getting help section to README

---

deps/build.jl
src/CPLEX.jl

Add support for 22.1.2
